# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/2048.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 456)
        MainWindow.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"background-image: url(images/a1.jpg);\n"
"")
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_button = QtWidgets.QPushButton(self.centralwidget)
        self.game_button.setGeometry(QtCore.QRect(190, 160, 141, 41))
        self.game_button.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.game_button.setToolTip("")
        self.game_button.setStyleSheet("\n"
"  text-decoration: none;\n"
"  color: #000;\n"
"  border: 3px solid;\n"
"  padding: 0.25em 0.5em;\n"
"  box-shadow: 1px 1px 0px 0px, 2px 2px 0px 0px, 3px 3px 0px 0px, 4px 4px 0px 0px, 5px 5px 0px 0px;\n"
"  position: relative;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"")
        self.game_button.setObjectName("game_button")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(190, 220, 141, 41))
        self.settings_button.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.settings_button.setStyleSheet("\n"
"  text-decoration: none;\n"
"  color: #000;\n"
"  border: 3px solid;\n"
"  padding: 0.25em 0.5em;\n"
"  box-shadow: 1px 1px 0px 0px, 2px 2px 0px 0px, 3px 3px 0px 0px, 4px 4px 0px 0px, 5px 5px 0px 0px;\n"
"  position: relative;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;")
        self.settings_button.setObjectName("settings_button")
        self.rules_button = QtWidgets.QPushButton(self.centralwidget)
        self.rules_button.setGeometry(QtCore.QRect(190, 280, 141, 41))
        self.rules_button.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.rules_button.setStyleSheet("\n"
"  text-decoration: none;\n"
"  color: #000;\n"
"  border: 3px solid;\n"
"  padding: 0.25em 0.5em;\n"
"  box-shadow: 1px 1px 0px 0px, 2px 2px 0px 0px, 3px 3px 0px 0px, 4px 4px 0px 0px, 5px 5px 0px 0px;\n"
"  position: relative;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;")
        self.rules_button.setObjectName("rules_button")
        self.author = QtWidgets.QPushButton(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(390, 430, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.author.setFont(font)
        self.author.setObjectName("author")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.game_button.setText(_translate("MainWindow", "Start Game"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.rules_button.setText(_translate("MainWindow", "Rules"))
        self.author.setText(_translate("MainWindow", "Author"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
