# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2048_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 456)
        Form.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"background-color: rgb(246, 210, 250);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 36, 81, 20))
        self.label.setStyleSheet("font: italic 14pt \"Century Gothic\";")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 111, 21))
        self.label_2.setStyleSheet("font: italic 14pt \"Century Gothic\";")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 70, 391, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton2.setChecked(True)
        self.radioButton2.setObjectName("radioButton2")
        self.horizontalLayout_2.addWidget(self.radioButton2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 190, 391, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton4.setChecked(True)
        self.radioButton4.setObjectName("radioButton4")
        self.horizontalLayout.addWidget(self.radioButton4)
        self.radioButton3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton3.setObjectName("radioButton3")
        self.horizontalLayout.addWidget(self.radioButton3)
        self.radioButton5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton5.setObjectName("radioButton5")
        self.horizontalLayout.addWidget(self.radioButton5)
        self.game_button = QtWidgets.QPushButton(Form)
        self.game_button.setGeometry(QtCore.QRect(150, 290, 141, 41))
        self.game_button.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.game_button.setToolTip("")
        self.game_button.setStyleSheet("\n"
"  text-decoration: none;\n"
"  color: #000;\n"
"  border: 2px solid;\n"
"  padding: 0.25em 0.5em;\n"
"  box-shadow: 1px 1px 0px 0px, 2px 2px 0px 0px, 3px 3px 0px 0px, 4px 4px 0px 0px, 5px 5px 0px 0px;\n"
"  position: relative;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"")
        self.game_button.setObjectName("game_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Theme"))
        self.label_2.setText(_translate("Form", "Resolution"))
        self.radioButton2.setText(_translate("Form", "Light"))
        self.radioButton.setText(_translate("Form", "Dark"))
        self.radioButton4.setText(_translate("Form", "500x500"))
        self.radioButton3.setText(_translate("Form", "450x600"))
        self.radioButton5.setText(_translate("Form", "800x800"))
        self.game_button.setText(_translate("Form", "Start Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
